name: Trigger New APK Build
on:
  push:
    branches:
      - main
    paths:
      - "package.json"
      - "app.json"
      - "eas.json"

jobs:
  build_apk:
    name: Generate Testing APK
    type: build
    params:
      platform: android
      profile: preview
